base_url = "https://psychonautgirl.space/blog"
# theme = "zola.386"

default_language = "en"
title = "Do cyborgs dream of bionic sheep?"
#description = "A Rotkäppchen exploration of the cyber universe"

highlight_code = true
compile_sass = true
generate_rss = true
build_search_index = true

taxonomies = [
  {name="categories", rss=true},
  {name="tags", rss=true},
]

[extra]
author = "Mari-chan"
year = "2021"

keywords = "zola, theme, retro, hacking"
theme_color = "black"
zola386_menu = [
  {path="", name="Home"},
  {path="categories", name="Categories"},
  {path="tags", name="Tags"},
  {path="about", name="About"},
]

### THIRD PARTY
# google_analytics = "UA-012345-67"
# disqus = "disqus-user"

### SOCIAL MEDIA
image = "https://avatars.githubusercontent.com/u/17600982?v=4"
twitter_user = "mari_meir"
linkedin_user = "mariana-meireles"
github_user = "marimeireles"
# gitlab_user = ""

### I18N WORDS
label_tags = "Tags"
label_tag = "Tag"
label_categories = "Categories"
label_category = "Category"
label_author = "Author"
label_date = "Date"
label_taxonomy = "Taxonomy"
label_reading = "Reading time"
label_read_more = "Read more"
